<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-03T23:00:23 IST" name="Suite" finished-at="2025-06-03T23:00:48 IST" duration-ms="25052">
    <groups>
    </groups>
    <test started-at="2025-06-03T23:00:23 IST" name="Test" finished-at="2025-06-03T23:00:48 IST" duration-ms="25052">
      <class name="testCases.Error_Scenario_Test">
        <test-method is-config="true" signature="intializeDriver()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:24 IST" name="intializeDriver" finished-at="2025-06-03T23:00:28 IST" duration-ms="4606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intializeDriver -->
        <test-method is-config="true" signature="initPageObjects()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:28 IST" name="initPageObjects" finished-at="2025-06-03T23:00:28 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initPageObjects -->
        <test-method signature="IncorrectUserPass(java.lang.String,java.lang.String)[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:28 IST" name="IncorrectUserPass" finished-at="2025-06-03T23:00:29 IST" duration-ms="966" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[invalid_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wrong_pass]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The error message when invalid user trying to login is not as expected.] but found [Epic sadface: Username and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The error message when invalid user trying to login is not as expected.] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Error_Scenario_Test.IncorrectUserPass(Error_Scenario_Test.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IncorrectUserPass -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:29 IST" name="closeDriver" finished-at="2025-06-03T23:00:30 IST" duration-ms="638" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="intializeDriver()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:30 IST" name="intializeDriver" finished-at="2025-06-03T23:00:33 IST" duration-ms="3046" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intializeDriver -->
        <test-method signature="LoginRedirectTest()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:33 IST" name="LoginRedirectTest" finished-at="2025-06-03T23:00:36 IST" duration-ms="2685" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Unable to access inventory page without login.] but found [Epic sadface: You can only access '/inventory.html' when you are logged in.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Unable to access inventory page without login.] but found [Epic sadface: You can only access '/inventory.html' when you are logged in.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Error_Scenario_Test.LoginRedirectTest(Error_Scenario_Test.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginRedirectTest -->
        <test-method is-config="true" signature="initPageObjects()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:33 IST" name="initPageObjects" finished-at="2025-06-03T23:00:33 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initPageObjects -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:36 IST" name="closeDriver" finished-at="2025-06-03T23:00:36 IST" duration-ms="599" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="intializeDriver()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:36 IST" name="intializeDriver" finished-at="2025-06-03T23:00:39 IST" duration-ms="2947" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intializeDriver -->
        <test-method is-config="true" signature="initPageObjects()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:39 IST" name="initPageObjects" finished-at="2025-06-03T23:00:39 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initPageObjects -->
        <test-method signature="SessionAfterLogoutTest(java.lang.String,java.lang.String)[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:39 IST" name="SessionAfterLogoutTest" finished-at="2025-06-03T23:00:41 IST" duration-ms="1336" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Unable to access inventory page without login.] but found [Epic sadface: You can only access '/inventory.html' when you are logged in.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Unable to access inventory page without login.] but found [Epic sadface: You can only access '/inventory.html' when you are logged in.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testCases.Error_Scenario_Test.SessionAfterLogoutTest(Error_Scenario_Test.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SessionAfterLogoutTest -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:testCases.Error_Scenario_Test@3c46e67a]" started-at="2025-06-03T23:00:41 IST" name="closeDriver" finished-at="2025-06-03T23:00:42 IST" duration-ms="1353" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- testCases.Error_Scenario_Test -->
      <class name="testCases.E2E_ECom_Automation">
        <test-method is-config="true" signature="intializeDriver()[pri:0, instance:testCases.E2E_ECom_Automation@61322f9d]" started-at="2025-06-03T23:00:42 IST" name="intializeDriver" finished-at="2025-06-03T23:00:45 IST" duration-ms="3190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intializeDriver -->
        <test-method signature="E2E_Test(java.lang.String,java.lang.String)[pri:0, instance:testCases.E2E_ECom_Automation@61322f9d]" started-at="2025-06-03T23:00:45 IST" name="E2E_Test" finished-at="2025-06-03T23:00:48 IST" duration-ms="2724" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- E2E_Test -->
        <test-method is-config="true" signature="initPageObjects()[pri:0, instance:testCases.E2E_ECom_Automation@61322f9d]" started-at="2025-06-03T23:00:45 IST" name="initPageObjects" finished-at="2025-06-03T23:00:45 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initPageObjects -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:testCases.E2E_ECom_Automation@61322f9d]" started-at="2025-06-03T23:00:48 IST" name="closeDriver" finished-at="2025-06-03T23:00:48 IST" duration-ms="641" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- testCases.E2E_ECom_Automation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
